const message_constants = {
  Success: "Successful",
  US: "Updated Successfully",
  UpS: "Uploaded Successfully",
  DS: "Deleted Successfully",
  DoS: "Downloaded Successfully",
  CS: "Created Successfully",
  OK: "OK",
  Created: "Created!",
  NC: "No Content",
  UA: "Unauthorized",
  PR: "Payment Required",
  FB: "Forbidden",
  TMR: "Too Many Requests",
  ISE: "Internal Server Error",
  SU: "Service Unavailable",
  NI: "Not Implemented",
  PRS: "Password reset sucesssfully",
  NF: "NOT FOUND",
  PNF: "Profile not found",
  PaNF: "Patient not found",
  PhNF: "Physician not found",
  PrNF: "Provider not found",
  DNF: "Document not found",
  UNF: "User not found",
  FNF: "File not found",
  ANF: "Admin not found",
  RNF: "Request not found",
  AcNF: "Accounts not found",
  ONF: "Order not found",
  BNF: "Business not found",
  NDF: "No documents found",
  ERP: "Error resetting password",
  ESRPL: "Error sending reset password link",
  EFPD: "Error fetching profession data",
  EWD: "Error while deleting",
  EFRD: "Error fetching region data",
  EWDI: "Error while deleting information",
  EWEI: "Error while deleting information",
  EWEA: "Error while editing account",
  EWDA: "Error while deleting account",
  EWDN: "Error while deleting notes",
  EWDD: "Error while deleting document",
  EWDO: "Error while deleting order",
  EWDP: "Error while deleting profile",
  EWDB:"Error while deleting business",
  EWU: "Error while updating",
  EWCB: "Error while creating business",
  EWUB: "Error while updating business",
  EWSA: "Error while sending agreement to your mail",
  EFBD: "Error fetching business data",
  ESA: "Error sending Agreement",
  EWSM: "Error while sending mail!!!",
  NVFD: "No valid files found for download",
  FTU: "Failed to upload !!!",
  IERT: "Invalid or expired reset token",
  IEA: "Invalid Email Address",
  IS: "Invalid State !!!",
  IA: "Invalid Action !!!",
  IEM: "Invalid email address and mobile number",
  RPLSE: "Reset password link sent to your email",
  CRLS: "Create request link sent successfully",
  ASE: "Agreement sent to your email",
  ES: "Email Sent",
  MS: "Message Sent",
};

export default message_constants;
