const message_constants = {
  Success: "Successful",
  US: "Updated Successfully",
  UpS:"Uploaded Successfully",
  DS: "Deleted Successfully",
  DoS:"Downloaded Successfully",
  CS:"Created Successfully",
  OK: "OK",
  Created: "Created!",
  NC: "No Content",
  NF: "NOT FOUND",
  UA: "Unauthorized",
  PR: "Payment Required",
  FB: "Forbidden",
  TMR: "Too Many Requests",
  ISE: "Internal Server Error",
  SU: "Service Unavailable",
  NI: "Not Implemented",
  IEA: "Invalid Email Address",
  PRS: "Password reset sucesssfully",
  ERP: "Error resetting password",
  IERT: "Invalid or expired reset token",
  ESRPL: "Error sending reset password link",
  RPLSE: "Reset password link sent to your email",
  EFRD: "Error fetching region data",
  EFPD: "Error fetching profession data",
  PNF: "Profile not found",
  PaNF:"Patient not found",
  PhNF:"Physician not found",
  PrNF:"Provider not found",
  DNF:"Document not found",
  VNF:"Vendor not found",
  UNF:"User not found",
  FNF:"File not found",
  ANF: "Admin not found",
  RNF:"Request not found",
  AcNF: "Accounts not found",
  ONF:"Order not found",
  BNF:"Business not found",
  EWD:"Error while deleting",
  EWDI: "Error while deleting information",
  EWEI: "Error while deleting information",
  EWEA: "Error while editing account",
  EWDA: "Error while deleting account",
  EWDN: "Error while deleting notes",
  EWDD:"Error while deleting document",
  EWDO:"Error while deleting order",
  EWDP:"Error while deleting profile",
  EWU:"Error while updating",
  NVFD:"No valid files found for download",
  NDF:"No documents found",
  IA: "Invalid Action !!!",
  IS: "Invalid State !!!",
  FTU:"Failed to upload !!!",
  EFBD:"Error fetching business data",
  IEM:"Invalid email address and mobile number",
  EWSA: "Error while sending agreement to your mail",
  ASE:"Agreement sent to your email",
  ESA:"Error sending Agreement",
  CRLS:"Create request link sent successfully",
  ES:"Email Sent",
  MS:"Message Sent",
  EWSM:"Error while sending mail!!!"
};

export default message_constants;
