const message_constants = {
  OK: "OK",
  Success: "Successful",
  US: "Updated Successfully",
  UpS: "Uploaded Successfully",
  DS: "Deleted Successfully",
  DoS: "Downloaded Successfully",
  CS: "Created Successfully",
  SS: "Signed-Up Successfully",
  RC: "Request Created!!!",
  NC: "No Content",
  UA: "Unauthorized",
  PR: "Payment Required",
  FB: "Forbidden",
  TMR: "Too Many Requests",
  ISE: "Internal Server Error",
  SU: "Service Unavailable",
  NI: "Not Implemented",
  PRS: "Password reset sucesssfully",
  NF: "NOT FOUND",
  PNF: "Profile not found",
  PaNF: "Patient not found",
  PhNF: "Physician not found",
  PrNF: "Provider not found",
  DNF: "Document not found",
  UNF: "User not found",
  FNF: "File not found",
  FoNF: "Form not found",
  ANF: "Admin not found",
  RNF: "Request not found",
  AcNF: "Accounts not found",
  AccNF: "Access not found",
  ONF: "Order not found",
  BNF: "Business not found",
  NDF: "Documents not found",
  RegNF: "Region not found",
  LNF: "Logs not found",
  RoNF: "Role not found",
  ReNF: "Requestor not found",
  RP: "Registered Patient",
  PNR: "Patient not registered",
  ERP: "Error resetting password",
  ESRPL: "Error sending reset password link",
  EFPD: "Error fetching profession data",
  EWD: "Error while deleting",
  EFRD: "Error while fetching region data",
  EWDI: "Error while deleting information",
  EWEA: "Error while editing account",
  EWDA: "Error while deleting account",
  EWDN: "Error while deleting notes",
  EWDD: "Error while deleting document",
  EWDO: "Error while deleting order",
  EWDP: "Error while deleting profile",
  EWDB: "Error while deleting business",
  EWC: "Error while creating",
  EWDo: "Error while downloading",
  EWCB: "Error while creating business",
  EWCA: "Error while creating account",
  EWCAc: "Error while creating access",
  EWCR: "Error while creating request",
  EWCN: "Error while creating notes",
  EWCS: "Error while creating shifts",
  EWFS: "Error while finding shifts",
  EWU: "Error while updating",
  EWUB: "Error while updating business",
  EWSA: "Error while sending agreement to your mail",
  EFBD: "Error while fetching business data",
  ESA: "Error while sending Agreement",
  EWSM: "Error while sending mail!!!",
  EWCL: "Error while creating log",
  EWSL: "Error while creating link",
  EWCounting: "Error while counting",
  NVFD: "No valid files found for download",
  FTU: "Failed to upload !!!",
  FS: "Failed to Sign-Up",
  IERT: "Invalid or expired reset token",
  IEA: "Invalid Email Address",
  IS: "Invalid State !!!",
  IA: "Invalid Action !!!",
  IEM: "Invalid email address and mobile number",
  RPLSE: "Reset password link sent to your email",
  CRLS: "Create request link sent successfully",
  ASEM: "Agreement sent to your email and mobile number",
  ADBSA: "Address does not belong to service area",
  AV: "Address Verified !!!",
  AD: "Access Denied",
  ES: "Email Sent",
  MS: "Message Sent",
  UE: "User Exists!!!",
  EFNF: "Encounter form is not finalized",
  EFIF: "Encounter form is finalized",
  EFoNF: "Encounter form not found",
  PAC: "Patient Already Created !!!",
  KSD: "Kindly select documents first",
};

export default message_constants;
